name: Test
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test.yml
      - action.yml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test.yml
      - action.yml
  schedule:
    - cron: '30 05 * * 0'
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        distro: [Ubuntu, none]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./
        with:
          distro: ${{ matrix.distro }}
      - if: ${{ matrix.distro != 'none' }}
        run: cat /etc/os-release && uname -a
        shell: wsl-run {0}
      - if: ${{ matrix.distro != 'none' }}
        name: Run a multi-line script
        run: |
          ls -alh
          cat ${0} # prints the script itself
          echo "Hello, world!"
          echo "Bye, world!"
        shell: wsl-run {0}
