name: Test
on:
  push:
    paths:
      - .github/workflows/test.yml
      - action.yml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test.yml
      - action.yml
  schedule:
    - cron: '30 05 * * 0'
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        distro:
          - none # only enable wsl2 and don't install a distro
          - Ubuntu
          - Debian
          - kali-linux
          - Ubuntu-18.04
          - Ubuntu-20.04
          - Ubuntu-22.04
          - Ubuntu-24.04
          - OracleLinux_7_9
          - OracleLinux_8_7
          - OracleLinux_9_1
          - openSUSE-Leap-15.6
          - SUSE-Linux-Enterprise-15-SP5
          - SUSE-Linux-Enterprise-15-SP6
          - openSUSE-Tumbleweed
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./
        with:
          distro: ${{ matrix.distro }}
      - if: ${{ matrix.distro != 'none' }}
        run: cat /etc/os-release && uname -a
        shell: wsl-run {0}
      - if: ${{ matrix.distro != 'none' }}
        name: Run a multi-line script
        run: |
          ls -alh
          cat ${0} # prints the script itself
          echo "Hello, world!"
          echo "Bye, world!"
        shell: wsl-run {0}
